marque:
    path:     /
    defaults: { _controller: "HomeBundle:Marque:index" }

marque_show:
    path:     /{id}/show
    defaults: { _controller: "HomeBundle:Marque:show" }

marque_new:
    path:     /new
    defaults: { _controller: "HomeBundle:Marque:new" }

marque_create:
    path:     /create
    defaults: { _controller: "HomeBundle:Marque:create" }
    methods:  POST

marque_edit:
    path:     /{id}/edit
    defaults: { _controller: "HomeBundle:Marque:edit" }

marque_update:
    path:     /{id}/update
    defaults: { _controller: "HomeBundle:Marque:update" }
    methods:  [POST, PUT]

marque_delete:
    path:     /{id}/delete
    defaults: { _controller: "HomeBundle:Marque:delete" }
    methods:  [POST, DELETE]
